- name: Open OpenShift ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 22623/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 9090/tcp