apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
  labels:
    app: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        command: ["sleep", "infinity"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"  # Change to your preferred AWS region
