apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: UURIUUlOUzNXR0ZWRVBIOVdBMTU=
  aws_secret_access_key: eWpHRmFSZDM2MzlUd09ScmRDYlhEaEZoUFV2OHBzTWhoajFVZzRYOQ==
