apiVersion: v1
kind: Pod
metadata:
  name: nfs-mount-example
spec:
  containers:
    - name: web-server
      image: nginx
  volumeMounts:
    - name: nfs-export-pvc
      mountPath: /var/lib/www/html
  volumes:
    - name: nfs-export-pvc
      persistentVolumeClaim:
        claimName: nfs-pvc
        readOnly: false

