apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-nfs
  resources:
    requests:
      storage: 1Gi

