apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3cmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3cmd
  template:
    metadata:
      labels:
        app: s3cmd
    spec:
      containers:
      - name: s3cmd
        image: image-registry.openshift-image-registry.svc:5000/s3cmd-demo/s3cmd:latest
        command: ["sleep", "infinity"]
