---
- name: Prepare KVM host
  hosts: localhost
  become: true
  roles:
    - role: kvm-setup
    - role: firewall-config
    - role: cockpit-install

  tasks:
    - name: Ensure libvirt service is running
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Add user to libvirt group
      user:
        name: "eng_muhammedsabry"
        groups: libvirt
        append: yes