- name: Install Cockpit
  package:
    name: 
      - cockpit
      - cockpit-machines
    state: present

- name: Start and enable Cockpit
  systemd:
    name: cockpit
    state: started
    enabled: yes